[pelican]
author = "Elliot Simpson"
sitename = "MySite"

timezone  = "Pacific/Auckland"

default_lang = "en"

path = "content"

default_pagination = false

theme = "themes/plain-theme"

article_paths = []
page_paths = [""]
page_save_as = "{slug}.html"

static_paths = ["static", "images"]

index_save_as = ""

[[pelican.extra_path_metadata]]
origin = "static/favicon.ico"
path = "favicon.ico"

[[pelican.extra_path_metadata]]
origin = "images/logo.svg"
path = "logo.svg"

[publish]
site_url = "https://turbopelican.github.io"
relative_urls = false
feed_all_atom = "feeds/all.atom.xml"
category_feed_atom = "feeds/{slug}.atom.xml"
delete_output_directory = true
